// <auto-generated />
using System;
using CyH_Techno_Store.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyHTechnoStore.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250421204205_Tarjeta")]
    partial class Tarjeta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyH_Techno_Store.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Descripcion = "Dispositivos electrónicos portátiles utilizados para comunicarse mediante llamadas o mensajes.",
                            Nombre = "Teléfonos móviles"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Descripcion = "Equipos electrónicos de procesamiento de datos diseñados para uso personal y profesional.",
                            Nombre = "Computadoras portátiles"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Descripcion = "Dispositivos electrónicos con pantalla táctil utilizados para navegación, lectura y multimedia.",
                            Nombre = "Tabletas electrónicas"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Descripcion = "Aparatos electrónicos para visualización de contenido audiovisual con funciones de conectividad.",
                            Nombre = "Televisores inteligentes"
                        },
                        new
                        {
                            CategoriaId = 5,
                            Descripcion = "Componentes electrónicos complementarios como cargadores, fundas y cables de conexión digital.",
                            Nombre = "Accesorios electrónicos"
                        });
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.DetalleFacturaAdmins", b =>
                {
                    b.Property<int>("DetalleFacturaAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleFacturaAdminId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FacturaAdminId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleFacturaAdminId");

                    b.HasIndex("FacturaAdminId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleFacturaAdmins", (string)null);

                    b.HasData(
                        new
                        {
                            DetalleFacturaAdminId = 1,
                            Cantidad = 15,
                            FacturaAdminId = 1,
                            PrecioUnitario = 50940.99m,
                            ProductoId = 1
                        },
                        new
                        {
                            DetalleFacturaAdminId = 2,
                            Cantidad = 15,
                            FacturaAdminId = 1,
                            PrecioUnitario = 65940.00m,
                            ProductoId = 2
                        },
                        new
                        {
                            DetalleFacturaAdminId = 3,
                            Cantidad = 15,
                            FacturaAdminId = 2,
                            PrecioUnitario = 74970.00m,
                            ProductoId = 3
                        },
                        new
                        {
                            DetalleFacturaAdminId = 4,
                            Cantidad = 15,
                            FacturaAdminId = 2,
                            PrecioUnitario = 47999.40m,
                            ProductoId = 4
                        },
                        new
                        {
                            DetalleFacturaAdminId = 5,
                            Cantidad = 15,
                            FacturaAdminId = 3,
                            PrecioUnitario = 35940.00m,
                            ProductoId = 5
                        },
                        new
                        {
                            DetalleFacturaAdminId = 6,
                            Cantidad = 15,
                            FacturaAdminId = 3,
                            PrecioUnitario = 38999.99m,
                            ProductoId = 6
                        },
                        new
                        {
                            DetalleFacturaAdminId = 7,
                            Cantidad = 15,
                            FacturaAdminId = 4,
                            PrecioUnitario = 83940.00m,
                            ProductoId = 7
                        },
                        new
                        {
                            DetalleFacturaAdminId = 8,
                            Cantidad = 15,
                            FacturaAdminId = 4,
                            PrecioUnitario = 59999.40m,
                            ProductoId = 8
                        },
                        new
                        {
                            DetalleFacturaAdminId = 9,
                            Cantidad = 15,
                            FacturaAdminId = 5,
                            PrecioUnitario = 41940.00m,
                            ProductoId = 9
                        },
                        new
                        {
                            DetalleFacturaAdminId = 10,
                            Cantidad = 15,
                            FacturaAdminId = 5,
                            PrecioUnitario = 53999.50m,
                            ProductoId = 10
                        });
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.DetalleFacturas", b =>
                {
                    b.Property<int>("DetalleFacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleFacturaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleFacturaId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleFacturas", (string)null);

                    b.HasData(
                        new
                        {
                            DetalleFacturaId = 1,
                            Cantidad = 5,
                            FacturaId = 1,
                            PrecioUnitario = 50940.99m,
                            ProductoId = 1
                        },
                        new
                        {
                            DetalleFacturaId = 2,
                            Cantidad = 5,
                            FacturaId = 1,
                            PrecioUnitario = 74970.00m,
                            ProductoId = 3
                        },
                        new
                        {
                            DetalleFacturaId = 3,
                            Cantidad = 5,
                            FacturaId = 2,
                            PrecioUnitario = 65940.00m,
                            ProductoId = 2
                        },
                        new
                        {
                            DetalleFacturaId = 4,
                            Cantidad = 5,
                            FacturaId = 2,
                            PrecioUnitario = 47999.40m,
                            ProductoId = 4
                        },
                        new
                        {
                            DetalleFacturaId = 5,
                            Cantidad = 5,
                            FacturaId = 3,
                            PrecioUnitario = 35940.00m,
                            ProductoId = 5
                        },
                        new
                        {
                            DetalleFacturaId = 6,
                            Cantidad = 5,
                            FacturaId = 3,
                            PrecioUnitario = 38999.99m,
                            ProductoId = 6
                        },
                        new
                        {
                            DetalleFacturaId = 7,
                            Cantidad = 5,
                            FacturaId = 4,
                            PrecioUnitario = 53999.50m,
                            ProductoId = 10
                        },
                        new
                        {
                            DetalleFacturaId = 8,
                            Cantidad = 5,
                            FacturaId = 4,
                            PrecioUnitario = 83940.00m,
                            ProductoId = 7
                        },
                        new
                        {
                            DetalleFacturaId = 9,
                            Cantidad = 5,
                            FacturaId = 5,
                            PrecioUnitario = 41940.00m,
                            ProductoId = 9
                        },
                        new
                        {
                            DetalleFacturaId = 10,
                            Cantidad = 5,
                            FacturaId = 5,
                            PrecioUnitario = 59999.40m,
                            ProductoId = 8
                        });
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.FacturaAdmins", b =>
                {
                    b.Property<int>("FacturaAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaAdminId"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("FacturaAdminId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("FacturaAdmins");

                    b.HasData(
                        new
                        {
                            FacturaAdminId = 1,
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProveedorId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            FacturaAdminId = 2,
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProveedorId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            FacturaAdminId = 3,
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProveedorId = 3,
                            UsuarioId = 3
                        },
                        new
                        {
                            FacturaAdminId = 4,
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProveedorId = 4,
                            UsuarioId = 4
                        },
                        new
                        {
                            FacturaAdminId = 5,
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProveedorId = 5,
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Facturas", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Facturas");

                    b.HasData(
                        new
                        {
                            FacturaId = 1,
                            FechaRegistro = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 6
                        },
                        new
                        {
                            FacturaId = 2,
                            FechaRegistro = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 7
                        },
                        new
                        {
                            FacturaId = 3,
                            FechaRegistro = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 8
                        },
                        new
                        {
                            FacturaId = 4,
                            FechaRegistro = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 9
                        },
                        new
                        {
                            FacturaId = 5,
                            FechaRegistro = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 10
                        });
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            CategoriaId = 1,
                            Descripcion = "Teléfono móvil con pantalla AMOLED y triple cámara de alta resolución.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://cdn1.smartprix.com/rx-izLSMVlI0-w1200-h1200/zLSMVlI0.jpg",
                            Nombre = "Samsung Galaxy S23",
                            PrecioUnitario = 50940.99m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 2,
                            CategoriaId = 1,
                            Descripcion = "Teléfono inteligente con tecnología Face ID y cámara de 48 MP.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://phonesdata.com/files/models/Apple-iPhone-14-Pro-907.jpg",
                            Nombre = "iPhone 14 Pro",
                            PrecioUnitario = 65940.00m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 3,
                            CategoriaId = 2,
                            Descripcion = "Laptop ultradelgada con pantalla táctil y procesador Intel i7.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://i.pcmag.com/imagery/reviews/06Ug0e0tlPFOh5qZAAcpq10-1.fit_lim.size_1200x630.v1688849689.jpg",
                            Nombre = "Dell XPS 13",
                            PrecioUnitario = 74970.00m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 4,
                            CategoriaId = 2,
                            Descripcion = "Computadora portátil con buen rendimiento para el trabajo diario.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://vitinhthienan.vn/upload/hinhanh/hp-all/ban-phim-laptop-hp/keyboard-hp-15-ab030tu/hp-15-ab030tu.jpg",
                            Nombre = "HP Pavilion 15",
                            PrecioUnitario = 47999.40m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 5,
                            CategoriaId = 3,
                            Descripcion = "Tableta de alto rendimiento con chip M1 y pantalla de 10.9 pulgadas.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://cdn.arstechnica.net/wp-content/uploads/2022/03/2022-iPad-Air-front-on-800x546.jpeg",
                            Nombre = "iPad Air 2022",
                            PrecioUnitario = 35940.00m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 6,
                            CategoriaId = 3,
                            Descripcion = "Tableta Android con gran rendimiento y pantalla AMOLED.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://www.zdnet.com/a/img/2022/07/17/fd8b66a7-f705-42d6-af93-08afa6c0965a/samsung-galaxy-tab-s8-ultra-8.jpg",
                            Nombre = "Samsung Galaxy Tab S8",
                            PrecioUnitario = 38999.99m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 7,
                            CategoriaId = 4,
                            Descripcion = "Televisor OLED con resolución 4K y compatibilidad con Dolby Vision.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://th.bing.com/th/id/OIP.LApG9RSTogWAqc7KM05JAgHaE6?rs=1&pid=ImgDetMain",
                            Nombre = "LG OLED C2 55",
                            PrecioUnitario = 83940.00m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 8,
                            CategoriaId = 4,
                            Descripcion = "Smart TV de 55 pulgadas con tecnología QLED y control por voz.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://th.bing.com/th/id/OIP.zYVsmU5Mk9SPgGfjTkmk4AHaE8?rs=1&pid=ImgDetMain",
                            Nombre = "Samsung QLED Q70",
                            PrecioUnitario = 59999.40m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 9,
                            CategoriaId = 5,
                            Descripcion = "Cámara digital sin espejo ideal para fotografía profesional.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://www.bhphotovideo.com/images/images1000x1000/canon_4728c006_eos_m50_mark_ii_1598385.jpg",
                            Nombre = "Canon EOS M50",
                            PrecioUnitario = 41940.00m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoId = 10,
                            CategoriaId = 5,
                            Descripcion = "Cámara compacta de lentes intercambiables con enfoque automático rápido.",
                            FechaRegistro = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://i5.walmartimages.com/asr/49d86635-3a17-4550-a3ac-937b3bd546a7_1.007c196265cf588fec8a2911a6659373.jpeg",
                            Nombre = "Sony Alpha a6400",
                            PrecioUnitario = 53999.50m,
                            Stock = 10
                        });
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Proveedores", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            ProveedorId = 1,
                            Correo = "contacto@tecnomundo.com",
                            FechaRegistro = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Tecno Mundo",
                            RNC = "123456789",
                            Telefono = "+18294321010"
                        },
                        new
                        {
                            ProveedorId = 2,
                            Correo = "ventas@electronicalopez.com",
                            FechaRegistro = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Electronica López",
                            RNC = "987654321",
                            Telefono = "+18095551234"
                        },
                        new
                        {
                            ProveedorId = 3,
                            Correo = "proveedor@megabyte.com",
                            FechaRegistro = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Mega Byte",
                            RNC = "456789123",
                            Telefono = "+18097894567"
                        },
                        new
                        {
                            ProveedorId = 4,
                            Correo = "info@electrodigital.com",
                            FechaRegistro = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Electro Digital",
                            RNC = "321654987",
                            Telefono = "+18296471230"
                        },
                        new
                        {
                            ProveedorId = 5,
                            Correo = "servicio@conectadordr.com",
                            FechaRegistro = new DateTime(2024, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Conectador RD",
                            RNC = "789123456",
                            Telefono = "+18093001234"
                        });
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroTarjeta")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Correo = "AdminPedro@gmail.com",
                            Direccion = "Calle Principal #1",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "1234567890123456789",
                            Password = "Pedro50...",
                            Role = "Admin",
                            Telefono = "8091234567",
                            UserName = "AdminPedro"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Correo = "AdminJose@gmail.com",
                            Direccion = "Avenida Siempre Viva #2",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "9876543210987654321",
                            Password = "Josep777",
                            Role = "Admin",
                            Telefono = "8092345678",
                            UserName = "AdminJose"
                        },
                        new
                        {
                            UsuarioId = 3,
                            Correo = "AdminSusan@gmail.com",
                            Direccion = "Calle Luna #3",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "1111222233334444555",
                            Password = "GatitaLinda15",
                            Role = "Admin",
                            Telefono = "8093456789",
                            UserName = "AdminSusan"
                        },
                        new
                        {
                            UsuarioId = 4,
                            Correo = "AdminVannesa@gmail.com",
                            Direccion = "Calle Sol #4",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "5555666677778888999",
                            Password = "Venaros60...",
                            Role = "Admin",
                            Telefono = "8094567890",
                            UserName = "AdminVannesa"
                        },
                        new
                        {
                            UsuarioId = 5,
                            Correo = "AdminJuan@gmail.com",
                            Direccion = "Calle 5 de Abril",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "1122334455667788990",
                            Password = "Master...200M",
                            Role = "Admin",
                            Telefono = "8291234567",
                            UserName = "AdminJuan"
                        },
                        new
                        {
                            UsuarioId = 6,
                            Correo = "FloresJJJ@gmail.com",
                            Direccion = "Avenida Las Palmas",
                            FechaRegistro = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "9988776655443322110",
                            Password = "Mis12Flores",
                            Role = "User",
                            Telefono = "8292345678",
                            UserName = "FloresJJJ"
                        },
                        new
                        {
                            UsuarioId = 7,
                            Correo = "Tengo4Lobos@gmail.com",
                            Direccion = "Residencial Brisas del Este",
                            FechaRegistro = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "1234432112344321123",
                            Password = "Lobos9999",
                            Role = "User",
                            Telefono = "8493456789",
                            UserName = "LoboAterrador"
                        },
                        new
                        {
                            UsuarioId = 8,
                            Correo = "Melon14@gmail.com",
                            Direccion = "Villa Mella, Santo Domingo",
                            FechaRegistro = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "3211233211233211234",
                            Password = "van999Plantas",
                            Role = "User",
                            Telefono = "8494567890",
                            UserName = "PlantasMuchas"
                        },
                        new
                        {
                            UsuarioId = 9,
                            Correo = "ResposteraJulia@gmail.com",
                            Direccion = "Ensanche La Fe",
                            FechaRegistro = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "1231231231231231231",
                            Password = "PastelDePapa20",
                            Role = "User",
                            Telefono = "8095678901",
                            UserName = "ResposteraJulia"
                        },
                        new
                        {
                            UsuarioId = 10,
                            Correo = "MarVelous@gmail.com",
                            Direccion = "Zona Colonial",
                            FechaRegistro = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "3213213213213213213",
                            Password = "VenusVSTierra",
                            Role = "User",
                            Telefono = "8295678901",
                            UserName = "Mariano111"
                        });
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.DetalleFacturaAdmins", b =>
                {
                    b.HasOne("CyH_Techno_Store.Models.FacturaAdmins", "FacturaAdmins")
                        .WithMany("DetalleFacturaAdmin")
                        .HasForeignKey("FacturaAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyH_Techno_Store.Models.Productos", "Productos")
                        .WithMany("DetalleFacturaAdmin")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacturaAdmins");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.DetalleFacturas", b =>
                {
                    b.HasOne("CyH_Techno_Store.Models.Facturas", "Facturas")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyH_Techno_Store.Models.Productos", "Productos")
                        .WithMany("DetalleFactura")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facturas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.FacturaAdmins", b =>
                {
                    b.HasOne("CyH_Techno_Store.Models.Proveedores", "Proveedores")
                        .WithMany("FacturaAdmin")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CyH_Techno_Store.Models.Usuarios", "Usuarios")
                        .WithMany("FacturasAdmin")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedores");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Facturas", b =>
                {
                    b.HasOne("CyH_Techno_Store.Models.Usuarios", "Usuarios")
                        .WithMany("Facturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Productos", b =>
                {
                    b.HasOne("CyH_Techno_Store.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.FacturaAdmins", b =>
                {
                    b.Navigation("DetalleFacturaAdmin");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Facturas", b =>
                {
                    b.Navigation("DetalleFacturas");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Productos", b =>
                {
                    b.Navigation("DetalleFactura");

                    b.Navigation("DetalleFacturaAdmin");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Proveedores", b =>
                {
                    b.Navigation("FacturaAdmin");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Usuarios", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("FacturasAdmin");
                });
#pragma warning restore 612, 618
        }
    }
}
