// <auto-generated />
using System;
using CyH_Techno_Store.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyHTechnoStore.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250410131118_primera")]
    partial class primera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyH_Techno_Store.Models.DetalleFacturass", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FacturasId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductosId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("FacturasId");

                    b.HasIndex("ProductosId");

                    b.ToTable("DetallesFacturas");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Facturass", b =>
                {
                    b.Property<int>("FacturasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturasId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("FacturasId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Facturass");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Productoss", b =>
                {
                    b.Property<int>("ProductosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductosId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductosId");

                    b.ToTable("Productoss");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.UserAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroTarjeta")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserAccountss", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "calle 18",
                            FechaRegistro = new DateTime(2020, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "1234567891456978524",
                            Password = "Qwe123...",
                            Role = "Admin",
                            Telefono = "8094627895",
                            UserName = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "calle 890",
                            FechaRegistro = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroTarjeta = "999999999999999999",
                            Password = "Asd123...",
                            Role = "User",
                            Telefono = "8094627111",
                            UserName = "Usuario"
                        });
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.DetalleFacturass", b =>
                {
                    b.HasOne("CyH_Techno_Store.Models.Facturass", "Facturas")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyH_Techno_Store.Models.Productoss", "Productos")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facturas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Facturass", b =>
                {
                    b.HasOne("CyH_Techno_Store.Models.UserAccounts", "Usuario")
                        .WithMany("Facturass")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Facturass", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.Productoss", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("CyH_Techno_Store.Models.UserAccounts", b =>
                {
                    b.Navigation("Facturass");
                });
#pragma warning restore 612, 618
        }
    }
}
